#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# QA server: Postgres + Anvil + deploy + indexer on loopback; writes .deploy/local.env for laptop scp.
# Prerequisites: Docker, Foundry, jq, curl, Rust (indexer). Optional repo-root .env for QA_SSH_HOST / overrides.
#
# Laptop: SSH -L (see make qa-tunnel-help), scp .deploy/local.env, scripts/qa/write-frontend-env-local.sh, npm run dev.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
  _QA_HI=$'\033[93;1m'
  _QA_RST=$'\033[0m'
else
  _QA_HI=''
  _QA_RST=''
fi
printf '%b\n' "${_QA_HI}┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${_QA_RST}"
printf '%b\n' "${_QA_HI}┃  REMINDER: SSH tunnel + laptop steps print at the END of this run        ┃${_QA_RST}"
printf '%b\n' "${_QA_HI}┃  Reprint anytime: make qa-tunnel-help                                     ┃${_QA_RST}"
printf '%b\n' "${_QA_HI}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${_QA_RST}"
echo ""

echo "==> Tearing down prior QA stack (Anvil, indexer, Postgres container)..."
chmod +x "$REPO_ROOT/scripts/qa/stop-qa.sh" 2>/dev/null || true
"$REPO_ROOT/scripts/qa/stop-qa.sh"

if [[ -f "$REPO_ROOT/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$REPO_ROOT/.env"
  set +a
fi
# shellcheck source=/dev/null
source "$REPO_ROOT/scripts/qa/qa-host.env"

export QA_USE_FIXED_INDEXER_PORT=1
export RPC_URL
export ANVIL_PORT
export PG_HOST_PORT
export INDEXER_PORT
export DOCKER_PG

echo "==> Starting full local Anvil stack (fixed indexer port ${INDEXER_PORT})..."
chmod +x "$REPO_ROOT/scripts/start-local-anvil-stack.sh" 2>/dev/null || true
bash "$REPO_ROOT/scripts/start-local-anvil-stack.sh"

REGISTRY="${REPO_ROOT}/contracts/deployments/local-anvil-registry.json"
[[ -f "$REGISTRY" ]] || {
  echo "[start-qa] Missing registry ${REGISTRY}" >&2
  exit 1
}

DEPLOY_DIR="${REPO_ROOT}/.deploy"
mkdir -p "$DEPLOY_DIR"

TC="$(jq -r '.contracts.TimeCurve' "$REGISTRY")"
RT="$(jq -r '.contracts.RabbitTreasury' "$REGISTRY")"
NFT="$(jq -r '.contracts.LeprechaunNFT' "$REGISTRY")"
FR="$(jq -r '.contracts.FeeRouter' "$REGISTRY")"
RR="$(jq -r '.contracts.ReferralRegistry' "$REGISTRY")"
CHAIN_ID="$(jq -r '.chainId' "$REGISTRY")"

INDEXER_URL="http://127.0.0.1:${INDEXER_PORT}"

cat > "${DEPLOY_DIR}/local.env" << EOF
# Generated by scripts/qa/start-qa.sh — copy to laptop: .deploy/local.env
# Do not commit secrets; this file is gitignored.
CHAIN_ID=${CHAIN_ID}
VITE_CHAIN_ID=${CHAIN_ID}
RPC_URL=${RPC_URL}
VITE_RPC_URL=${RPC_URL}
VITE_INDEXER_URL=${INDEXER_URL}
VITE_TIMECURVE_ADDRESS=${TC}
VITE_RABBIT_TREASURY_ADDRESS=${RT}
VITE_LEPRECHAUN_NFT_ADDRESS=${NFT}
VITE_FEE_ROUTER_ADDRESS=${FR}
VITE_REFERRAL_REGISTRY_ADDRESS=${RR}
EOF

echo "==> Wrote ${DEPLOY_DIR}/local.env (scp this to your laptop clone)."

echo ""
echo "========================================================================"
echo "  start-qa finished successfully on this host."
echo "========================================================================"
chmod +x "$REPO_ROOT/scripts/qa/print-qa-tunnel-instructions.sh" 2>/dev/null || true
"$REPO_ROOT/scripts/qa/print-qa-tunnel-instructions.sh"
