#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Write frontend/.env.local for Vite on the laptop after SSH port forwards.
# Deploy artifact first (scp from QA): .deploy/local.env — then qa-host.env sets loopback URLs/ports.
#
# Usage (laptop):
#   scp user@qa:.../yieldomega/.deploy/local.env .deploy/local.env
#   ./scripts/qa/write-frontend-env-local.sh
#   cd frontend && npm run dev
#
# Optional: ./scripts/qa/write-frontend-env-local.sh --urls-only
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_ENV="${REPO_ROOT}/.deploy/local.env"
FE_OUT="${REPO_ROOT}/frontend/.env.local"

URLS_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --urls-only) URLS_ONLY=1 ;;
    -h | --help)
      echo "Usage: ${0##*/} [--urls-only]"
      echo "  Writes frontend/.env.local from .deploy/local.env + scripts/qa/qa-host.env"
      echo "  --urls-only  allow missing .deploy/local.env; URLs only, contract addresses empty"
      exit 0
      ;;
  esac
done

if [[ ! -f "$DEPLOY_ENV" ]]; then
  if [[ "$URLS_ONLY" != "1" ]]; then
    echo "[write-frontend-env-local] Missing ${DEPLOY_ENV}" >&2
    echo "  Copy from the QA host after start-qa, then re-run. Example:" >&2
    echo "    scp USER@HOST:/path/to/yieldomega/.deploy/local.env .deploy/local.env" >&2
    echo "  Or: $0 --urls-only  (RPC + indexer URLs only)" >&2
    exit 1
  fi
  echo "[write-frontend-env-local] No ${DEPLOY_ENV} — URLs only (--urls-only)." >&2
fi

set -a
if [[ -f "$DEPLOY_ENV" ]]; then
  # shellcheck source=/dev/null
  source <(sed 's/\r$//' "$DEPLOY_ENV")
fi
# shellcheck source=/dev/null
source "${REPO_ROOT}/scripts/qa/qa-host.env"
set +a

# qa-host wins for tunnel endpoints (must match ssh -L local ports).
export VITE_RPC_URL="${RPC_URL}"
export VITE_INDEXER_URL="http://127.0.0.1:${INDEXER_PORT}"
export VITE_CHAIN_ID="${VITE_CHAIN_ID:-${CHAIN_ID:-31337}}"

if [[ "$URLS_ONLY" == "1" ]] && [[ ! -f "$DEPLOY_ENV" ]]; then
  export VITE_TIMECURVE_ADDRESS=""
  export VITE_RABBIT_TREASURY_ADDRESS=""
  export VITE_LEPRECHAUN_NFT_ADDRESS=""
  export VITE_FEE_ROUTER_ADDRESS=""
  export VITE_REFERRAL_REGISTRY_ADDRESS=""
fi

mkdir -p "$(dirname "$FE_OUT")"

{
  echo "# Generated by scripts/qa/write-frontend-env-local.sh — do not commit"
  echo "VITE_CHAIN_ID=${VITE_CHAIN_ID}"
  echo "VITE_RPC_URL=${VITE_RPC_URL}"
  echo "VITE_INDEXER_URL=${VITE_INDEXER_URL}"
  echo "VITE_TIMECURVE_ADDRESS=${VITE_TIMECURVE_ADDRESS:-}"
  echo "VITE_RABBIT_TREASURY_ADDRESS=${VITE_RABBIT_TREASURY_ADDRESS:-}"
  echo "VITE_LEPRECHAUN_NFT_ADDRESS=${VITE_LEPRECHAUN_NFT_ADDRESS:-}"
  echo "VITE_FEE_ROUTER_ADDRESS=${VITE_FEE_ROUTER_ADDRESS:-}"
  echo "VITE_REFERRAL_REGISTRY_ADDRESS=${VITE_REFERRAL_REGISTRY_ADDRESS:-}"
} >"$FE_OUT"

echo "[write-frontend-env-local] Wrote ${FE_OUT}"
