#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Deploy DeployDev to Anvil (or an existing RPC) and write bots/timecurve/.env.local for the TimeCurve bot.
#
# Usage (from repo root):
#   bash scripts/anvil-export-bot-env.sh              # start Anvil, deploy, write .env.local
#   bash scripts/anvil-export-bot-env.sh --no-anvil   # deploy only (Anvil already on ANVIL_PORT / default 8545)
#
# Options:
#   --no-anvil          Do not start Anvil; use RPC at http://127.0.0.1:${ANVIL_PORT:-8545}
#   --output PATH       Write env file here (default: bots/timecurve/.env.local)
#   --port PORT         Anvil port (default: 8545 or ANVIL_PORT)
#
# Anvil is left running when this script starts it (stop manually: kill <pid>).
# Prerequisites: forge, cast, anvil (unless --no-anvil); same as scripts/e2e-anvil.sh.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
START_ANVIL=1
OUT_FILE="${ROOT}/bots/timecurve/.env.local"
PORT="${ANVIL_PORT:-8545}"

while [ $# -gt 0 ]; do
  case "$1" in
    --no-anvil) START_ANVIL=0; shift ;;
    --output) OUT_FILE="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | grep -v '^#!/' | sed 's/^# //' | sed 's/^#//'
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

RPC="http://127.0.0.1:${PORT}"
DEPLOY_LOG="$(mktemp)"
# shellcheck source=scripts/lib/anvil_deploy_dev.sh
source "${ROOT}/scripts/lib/anvil_deploy_dev.sh"

cleanup_tmp() { rm -f "${DEPLOY_LOG}"; }
trap cleanup_tmp EXIT

if ! command -v forge >/dev/null || ! command -v cast >/dev/null; then
  echo "Need forge and cast on PATH (Foundry)." >&2
  exit 1
fi

if [ "${START_ANVIL}" -eq 1 ]; then
  if ! command -v anvil >/dev/null; then
    echo "Need anvil on PATH, or use --no-anvil with a running node." >&2
    exit 1
  fi
  echo "Starting anvil on ${RPC} (MegaEVM-sized code: --code-size-limit 0x80000)..."
  anvil --host 127.0.0.1 --port "${PORT}" --code-size-limit 0x80000 >/tmp/yieldomega_anvil_bot_env.log 2>&1 &
  ANVIL_PID=$!
  echo "Anvil PID=${ANVIL_PID} (leave running for local bot / frontend; stop with: kill ${ANVIL_PID})"
  for _ in $(seq 1 60); do
    if cast block-number --rpc-url "${RPC}" >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done
  if ! cast block-number --rpc-url "${RPC}" >/dev/null 2>&1; then
    echo "Anvil did not become ready at ${RPC}." >&2
    exit 1
  fi
fi

yieldomega_anvil_deploy_dev

AA=$(cast call "${TC}" "acceptedAsset()(address)" --rpc-url "${RPC}" | head -1 || true)
# cast may return "0x0000... padded" — normalize to 42-char address
if [ -n "${AA}" ]; then
  AA=$(echo "${AA}" | grep -oE '0x[a-fA-F0-9]{40}' | head -1 || true)
fi

mkdir -p "$(dirname "${OUT_FILE}")"
umask 077
cat > "${OUT_FILE}" <<EOF
# Generated by scripts/anvil-export-bot-env.sh — do not commit (see .gitignore).
YIELDOMEGA_RPC_URL=${RPC}
YIELDOMEGA_CHAIN_ID=31337
YIELDOMEGA_TIMECURVE_ADDRESS=${TC}
YIELDOMEGA_RABBIT_TREASURY_ADDRESS=${RT}
YIELDOMEGA_LEPRECHAUN_NFT_ADDRESS=${NFT}
YIELDOMEGA_ACCEPTED_ASSET_ADDRESS=${AA}
# Optional: YIELDOMEGA_PRIVATE_KEY=  (Anvil account #0 key from Foundry docs — local only)
EOF

echo "Wrote ${OUT_FILE}"
echo "Load with: set -a && source ${OUT_FILE} && set +a"
echo "Or from bots/timecurve: export \$(grep -v '^#' .env.local | xargs)"
