#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copy contract/RPC settings from frontend/.env.local (VITE_*) to bots/timecurve/.env.local (YIELDOMEGA_*)
# without redeploying contracts. Use after scripts/start-local-anvil-stack.sh or any workflow that
# writes frontend/.env.local.
#
# Unlike scripts/anvil-export-bot-env.sh, this does **not** run forge or change chain state.
#
# Usage (from repo root):
#   bash scripts/sync-bot-env-from-frontend.sh
#   bash scripts/sync-bot-env-from-frontend.sh --frontend-env path/to/.env.local
#   bash scripts/sync-bot-env-from-frontend.sh --output bots/timecurve/.env.local
#
# Requires: cast on PATH (reads acceptedAsset from TimeCurve).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_ENV="${ROOT}/frontend/.env.local"
OUT_FILE="${ROOT}/bots/timecurve/.env.local"

while [ $# -gt 0 ]; do
  case "$1" in
    --frontend-env) FRONTEND_ENV="$2"; shift 2 ;;
    --output) OUT_FILE="$2"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | grep -v '^#!/' | sed 's/^# //' | sed 's/^#//'
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ ! -f "$FRONTEND_ENV" ]]; then
  echo "Missing ${FRONTEND_ENV} (create it first, e.g. bash scripts/start-local-anvil-stack.sh)." >&2
  exit 1
fi

if ! command -v cast >/dev/null 2>&1; then
  echo "Need cast on PATH (Foundry)." >&2
  exit 1
fi

get_vite() {
  local key="$1"
  grep "^${key}=" "$FRONTEND_ENV" | tail -1 | cut -d= -f2- | tr -d '\r'
}

RPC_URL="$(get_vite VITE_RPC_URL)"
TC="$(get_vite VITE_TIMECURVE_ADDRESS)"
RT="$(get_vite VITE_RABBIT_TREASURY_ADDRESS)"
NFT="$(get_vite VITE_LEPRECHAUN_NFT_ADDRESS)"
CHAIN_ID="$(get_vite VITE_CHAIN_ID)"

if [[ -z "${RPC_URL}" || -z "${TC}" || -z "${RT}" || -z "${NFT}" ]]; then
  echo "Need VITE_RPC_URL, VITE_TIMECURVE_ADDRESS, VITE_RABBIT_TREASURY_ADDRESS, VITE_LEPRECHAUN_NFT_ADDRESS in ${FRONTEND_ENV}" >&2
  exit 1
fi

if [[ -z "${CHAIN_ID}" ]]; then
  CHAIN_ID=31337
fi

AA="$(cast call "${TC}" "acceptedAsset()(address)" --rpc-url "${RPC_URL}" | grep -oE '0x[a-fA-F0-9]{40}' | head -1 || true)"
if [[ -z "${AA}" ]]; then
  echo "Could not read acceptedAsset from TimeCurve at ${TC} (is RPC up?)." >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")"
umask 077
cat > "${OUT_FILE}" <<EOF
# Generated by scripts/sync-bot-env-from-frontend.sh — do not commit (see .gitignore).
YIELDOMEGA_RPC_URL=${RPC_URL}
YIELDOMEGA_CHAIN_ID=${CHAIN_ID}
YIELDOMEGA_TIMECURVE_ADDRESS=${TC}
YIELDOMEGA_RABBIT_TREASURY_ADDRESS=${RT}
YIELDOMEGA_LEPRECHAUN_NFT_ADDRESS=${NFT}
YIELDOMEGA_ACCEPTED_ASSET_ADDRESS=${AA}
# Optional: YIELDOMEGA_PRIVATE_KEY=  (Anvil account #0 key from Foundry docs — local only)
EOF

echo "Wrote ${OUT_FILE}"
echo "Load with: set -a && source ${OUT_FILE} && set +a"
